export { default as react } from "./react.svg"
export { default as millLogo } from "./mill-logo.png"
export { default as agregarSvg } from "./agregar.svg"
export { default as cartSvg } from "./cart.svg"
export { default as deleteSvg } from "./delete.svg"
export { default as filtersSvg } from "./filters.svg"
export { default as homeSvg } from "./home.svg"
export { default as lupaSvg } from "./lupa.svg"
export { default as check } from "./check.svg"
export { default as reload } from "./reload.svg"
export const bg = "https://www.themillrestaurants.com/wp-content/themes/themills/img/home-bg.jpg"

